version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: first_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - first_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: first_php
    volumes:
      - ./src:/var/www/html
    networks:
      - first_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: first_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "first_db"
      MYSQL_USER: "first_user"
      MYSQL_PASSWORD: "first_password"
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - first_network

networks:
  first_network:
    driver: bridge

volumes:
  mysql_data:
